### PR TITLE
Change slug usage to encoded text

### LINKED ISSUE #209: Unable to Access Workspace when Creating a Workspace with non-English Language
**What happened**:
When creating a Workspace using a non-English language, specifically when using characters outside the English alphabet, the user is unable to access the Workspace. The slug creation process seems to be encountering issues when handling non-English characters.

**What you expected to happen**:
I expected to be able to create a Workspace using a non-English language and access it without any issues.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a new Workspace.
2. Use non-English characters (such as Korean, Chinese, etc.) during the Workspace creation process.
3. Try to access the created Workspace.

**Anything else we need to know?**:
It is important to ensure that the slug creation process can handle non-English characters to allow users to create Workspaces in different languages.

**Environment**:
- Operating system:
- Browser and version:
- CodePair version:

### PR DESCRIPTION
**Pull request by minai621**
**What this PR does / why we need it**:
This PR changes the method of handling text from using slugs to using encoded text. The previous slug generation method did not support all languages and returned empty strings when special characters like emojis were included. By switching to encoded text, we ensure compatibility with any type of text input.

**Which issue(s) this PR fixes**:

Fixes #209 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
The method for handling workspace names has been changed from slug generation to encoded text to support all languages and special characters.
```

**Additional documentation**:

```docs

```

**Checklist**:
- [x] Added relevant tests or not required
- [x] Didn't break anything

## Summary by CodeRabbit

- **New Features**
	- Enhanced validation for nickname and title fields in the creation modal, requiring a minimum of 2 characters.

- **Bug Fixes**
	- Improved handling of special characters in workspace and user nicknames by replacing the slugify function with encodeURIComponent, ensuring more accurate conflict detection and URL safety.

- **Refactor**
	- Cleaned up import statements across various services for better organization and clarity.

### CODE REVIEW

File: backend/src/workspaces/workspaces.controller.ts [hunk 1]
```diff
@@ -68,7 +68,7 @@ export class WorkspacesController {
 		@Req() req: AuthroizedRequest,
 		@Param("workspace_slug") workspaceSlug: string
 	): Promise<FindWorkspaceResponse> {
-		return this.workspacesService.findOneBySlug(req.user.id, workspaceSlug);
+		return this.workspacesService.findOneBySlug(req.user.id, encodeURIComponent(workspaceSlug));
```
Comment (devleejb) [inline backend/src/workspaces/workspaces.controller.ts:71]: I think we don't have to call `encodeURIComponent` here.
Because the parameter is already slug.

File: frontend/src/components/modals/CreateModal.tsx [hunk 2]
```diff
@@ -102,7 +108,7 @@ function CreateModal(props: CreateModalProps) {
 									type="submit"
 									variant="contained"
 									size="large"
-									disabled={Boolean(errorMessage)}
+									disabled={Boolean(errorMessage) || nickname.length < 2}
```
Comment (devleejb) [inline frontend/src/components/modals/CreateModal.tsx:111]: This is redundant.
When `nickname.length < 2`, errorMessage already exists.

**Review by devleejb — CHANGES_REQUESTED** [review]
And we have to add validation check in `CreateWorkspaceDto` and `ChangeNicknameDto`.

Validation Docs: https://docs.nestjs.com/techniques/validation

File: backend/src/workspaces/workspaces.controller.ts (hunk 1 above)
Comment (devleejb) [reply backend/src/workspaces/workspaces.controller.ts:71]: Oh, I see.
Then, I think it's okay.

**Comment by devleejb** [comment]
> > And we have to add validation check in `CreateWorkspaceDto` and `ChangeNicknameDto`.
> > Validation Docs: https://docs.nestjs.com/techniques/validation
> 
> Could you let me know which parts need validation?

For workspace title and user nickname should be checked both frontend in backend.

For example, in `CreateWorkspaceDto`

```Typescript
@ApiProperty({ description: "Title of project to create", type: String, maxLength: 2 })
@MinLength(2)
title: string;
```
(It also should be applied to swagger.)

**Review by devleejb — APPROVED** [review]
Thank you for your contribution.

**Comment by injae-kim** [comment]
Nice improvement @minai621! 👍👍
