### PR TITLE
Intergrate `YorkieIntelligence` into `ToolBar`

### LINKED ISSUE #267: Integrate `YorkieIntelligence` component into `FormatBar` component
**What happened**:
Currently, there is an issue where the `yorkie-intelligence` button moves with each change when adding or removing markdown symbols to the selected text using the format bar or keyboard shortcuts.

이슈

**What you expected to happen**:
Since `YorkieIntelligence.tsx` and `FormatBar.tsx` are rendered separately, integrating them into one component can resolve this issue and potentially enhance the user experience.

**How to reproduce it (as minimally and precisely as possible)**:
There are two proposed ideas to solved this problem:

1. Inserting the `YorkieIntelligence` component into the `FormatBar` component.
2. Creating a fixed navigation bar at the top of the `Editor` area and incorporating both the `FormatBar` and `YorkieIntelligence` components. This approach might increase the workload but could offer added convenience for users by including other markdown features like `h1, h2, h3`, `Image`, `Link`, etc.

Please consider which option would be more suitable and provide your insights.

### LINKED ISSUE #272: Yorkie Intelligence button remains visible after switching to read-only mode
**What happened**:
After switching to read-only mode in Yorkie, the Yorkie Intelligence button remains visible on the interface when it should disappear.

**What you expected to happen**:
The Yorkie Intelligence button should no longer be visible once the user switches to read-only mode.

**How to reproduce it (as minimally and precisely as possible)**:

https://github.com/user-attachments/assets/59c934c6-2e9e-441a-9402-7bdb9b03fd50

1. In editing mode, drag some text.
2. Change to view-only mode.

**Anything else we need to know?**:

**Environment**:
- Operating system: ALL
- Browser and version: ALL
- CodePair version: ALL

### PR DESCRIPTION
**Pull request by beberiche**
**What this PR does / why we need it**:
This PR integrates the `YorkieIntelligence` component within the `ToolBar` component and renames `FormatBar` to `ToolBar`. This change helps in resolving rendering issues during text drag operations and streamlines the component structure.

**Which issue(s) this PR fixes**:

Fixes #267 
(Maybe will be fixed #272 

**Special notes for your reviewer**:
- The `YorkieIntelligence` component is now part of `ToolBar`, which resolves rendering issues when dragging text.
- Unnecessary state values were removed, and the component's structure and styling were redesigned for better performance.
- An activation state has been added to the `YorkieIntelligence` component, which allows for dynamic styling and click events based on its active status.
스크린샷 2024-08-17 오후 1 33 38
스크린샷 2024-08-17 오후 1 31 27

</br>
</br>

**Does this PR introduce a user-facing change?**:

```release-note
Merge `yorkieIntelligence` component into `ToolBar` and rename `formatBar` to `ToolBar`
```

**Checklist**:
- [x] Added relevant tests or not required
- [x] Didn't break anything

## Summary by CodeRabbit

- **New Features**
	- Introduced a new `ToolBar` component, enhancing editing functionality.
	- Added a `ButtonGroup` to the `ToolBar` for improved interaction with formatting options.

- **UI Enhancements**
	- Adjusted styling for the `TooltipToggleButton`, improving button spacing.
	- Enhanced footer visibility toggle in the `YorkieIntelligence` component for better user experience.

- **Refactor**
	- Renamed components and state variables for clarity, transitioning from "FormatBar" to "ToolBar".
	- Streamlined logic by removing unnecessary state management in the `YorkieIntelligence` component.
	- Simplified the `DocumentIndex` component by removing unused imports and dependencies.

### CODE REVIEW

File: frontend/src/pages/workspace/document/Index.tsx [hunk 1]
```diff
@@ -8,15 +8,15 @@ import { useGetDocumentQuery } from "../../../hooks/api/workspaceDocument";
 import { useGetWorkspaceQuery } from "../../../hooks/api/workspace";
 import DocumentView from "../../../components/editor/DocumentView";
 import { useYorkieDocument } from "../../../hooks/useYorkieDocument";
-import YorkieIntelligence from "../../../components/editor/YorkieIntelligence";
-import { selectSetting } from "../../../store/settingSlice";
+// import YorkieIntelligence from "../../../components/editor/YorkieIntelligence";
+// import { selectSetting } from "../../../store/settingSlice";
```
Comment (devleejb) [inline frontend/src/pages/workspace/document/Index.tsx:12]: Please remove the unused code.

File: frontend/src/pages/workspace/document/Index.tsx [hunk 2]
```diff
@@ -8,15 +8,15 @@ import { useGetDocumentQuery } from "../../../hooks/api/workspaceDocument";
...
 
 function DocumentIndex() {
 	const dispatch = useDispatch();
 	const params = useParams();
 
 	const userStore = useSelector(selectUser);
-	const settingStore = useSelector(selectSetting);
+	// const settingStore = useSelector(selectSetting);
```
Comment (devleejb) [inline frontend/src/pages/workspace/document/Index.tsx:19]: Please remove the unused code.

File: frontend/src/components/editor/YorkieIntelligence.tsx [hunk 3]
```diff
@@ -1,79 +1,53 @@
...
+				onClick={handleFooterOpen}
+				sx={{
+					padding: "3px 5px",
+					border: "none",
+					"&:hover": {
+						border: "none",
+					},
+					filter: activated ? "none" : "grayscale(100%)",
+					pointerEvents: activated ? "auto" : "none",
+					opacity: activated ? 1 : 0.7,
```
Comment (devleejb) [inline frontend/src/components/editor/YorkieIntelligence.tsx:40]: We can use `disabled` props in `Button` component and delete this values.

File: frontend/src/components/editor/YorkieIntelligence.tsx [hunk 4]
```diff
@@ -1,79 +1,53 @@
...
-				)}
-			</Popper>
+				<img src="/yorkie.png" height={20} alt="yorkie_img" />
+				<Typography variant="subtitle1" fontSize={14}>
+					Yorkie Intelligence
+				</Typography>
+			</Button>
+
 			{footerOpen &&
+				activated &&
```
Comment (devleejb) [inline frontend/src/components/editor/YorkieIntelligence.tsx:50]: Why should we add `activated` here?
The value `footerOpen` seems that it can't be `true` when the `YorkieIntelligence` component is not rendered.

File: frontend/src/components/editor/FormatBar.tsx [hunk 5]
```diff
@@ -31,11 +32,21 @@ function FormatBar({
...
+				"& .MuiPopover-paper": {
+					display: "flex",
+					alignItems: "center",
+				},
+			}}
 		>
+			<ButtonGroup sx={{ height: "100%", margin: "3px 7px" }}>
+				<YorkieIntelligence />
+			</ButtonGroup>
+			<Box sx={{ borderLeft: 1, height: "15px", borderColor: "#dddddd" }} />
```
Comment (devleejb) [inline frontend/src/components/editor/FormatBar.tsx:45]: We can use `<Divider />` component instead of `Box`.

File: frontend/src/components/editor/FormatBar.tsx [hunk 6]
```diff
@@ -31,11 +32,21 @@ function FormatBar({
 				horizontal: "left",
 			}}
 			disableAutoFocus
+			sx={{
+				"& .MuiPopover-paper": {
+					display: "flex",
+					alignItems: "center",
+				},
+			}}
```
Comment (devleejb) [inline frontend/src/components/editor/FormatBar.tsx:40]: Instead of `sx` props, we can use `<Stack direction="row">...</Stack>`.

File: frontend/src/components/editor/FormatBar.tsx [hunk 7]
```diff
@@ -31,11 +32,21 @@ function FormatBar({
...
 		>
+			<ButtonGroup sx={{ height: "100%", margin: "3px 7px" }}>
```
Comment (devleejb) [inline frontend/src/components/editor/FormatBar.tsx:42]: I have a question.
Why should we use `ButtonGroup`?

File: frontend/src/components/editor/Editor.tsx [hunk 8]
```diff
@@ -185,11 +185,8 @@ function Editor() {
 						minHeight: "100%",
 					}}
 				/>
-				{Boolean(formatBarState.show && editorStore.cmView) && (
-					<FormatBar
-						formatBarState={formatBarState}
-						onChangeFormatBarState={setFormatBarState}
-					/>
+				{Boolean(toolBarState.show && editorStore.cmView) && (
```
Comment (devleejb) [inline frontend/src/components/editor/Editor.tsx:188]: I have a question.
Why should we add `editorStore.cmView` here?

File: frontend/src/components/editor/Editor.tsx [hunk 9]
```diff
@@ -73,18 +73,18 @@ function Editor() {
...
+					setToolBarState((prev) => ({
 						...prev,
 						show: true,
 						position: {
 							top: coords.top - 8,
-							left: coords.left + 190,
+							left: coords.left + 30,
 						},
 						selectedFormats: formats,
 					}));
```
Comment (devleejb) [inline frontend/src/components/editor/Editor.tsx:84]: It seems that we should change the position when changing the `FormatBar` component. (Is it right?)
For now, it is okay because this change will resolve the https://github.com/yorkie-team/codepair/issues/272, https://github.com/yorkie-team/codepair/issues/205.

Could you add the comment for this `TODO`?
```
TODO: Change the FormatBar rendering method.
```

File: frontend/src/components/editor/YorkieIntelligence.tsx [hunk 10]
```diff
@@ -1,79 +1,53 @@
...
 	const [intelligenceFooterPivot, setIntelligenceFooterPivot] = useState<Element | null>(null);
-	const [debouncedPivot, setDebouncedPivot] = useState<Element | null>(null);
 
-	useDebounce(
-		() => {
-			setDebouncedPivot(intelligenceHeaderPivot);
-		},
-		500,
-		[intelligenceHeaderPivot]
-	);
```
Comment (devleejb) [inline frontend/src/components/editor/YorkieIntelligence.tsx:21]: We should move the `debounce` logic and `Transition` options to `FormatBar`.

File: frontend/src/components/editor/FormatBar.tsx [hunk 11]
```diff
@@ -31,11 +32,21 @@ function FormatBar({
...
+				<YorkieIntelligence />
+			</ButtonGroup>
+			<Box sx={{ borderLeft: 1, height: "15px", borderColor: "#dddddd" }} />
 			<ToggleButtonGroup
-				sx={{ padding: "3px 5px" }}
+				sx={{ margin: "3px 7px" }}
```
Comment (devleejb) [inline frontend/src/components/editor/FormatBar.tsx:47]: The value `margin` can be removed by introduce `Stack` as a parent component.

**Review by devleejb — CHANGES_REQUESTED** [review]

File: frontend/src/components/editor/YorkieIntelligence.tsx (hunk 4 above)
Comment (beberiche) [reply frontend/src/components/editor/YorkieIntelligence.tsx]: Because, intelligenceFooterPivot 's type is `Element | null`. so, intelligenceFooterPivot cause type error by typescript compiler.

I changed code using if statement (type guard by falsy)

**Comment by beberiche** [comment]
@devleejb
I changed code for comments!

**Review by devleejb — APPROVED** [review]
Thank you for your contribution.

We actually use a scaling factor (https://mui.com/material-ui/customization/spacing/) for padding, margin, and spacing. However, I think it’s okay for now since these values will be adjusted when the design is finalized.
